export { TranslationValidator } from './validation';
export { TranslationApiClient } from './api-client';
export { TranslationFileOperations } from './file-operations';
export { DirectExportHelper } from './direct-export';
export { DiffDetector } from './diff-detector';
export type { GitDiffResult, DiffChange } from './diff-detector';
export { FileUpdater } from './file-updater';
export type { ParagraphUpdate, Paragraph, TranslatedParagraph } from './file-updater';
export { DiffValidator } from './diff-validator';
export { DiffProcessor } from './diff-processor';
export { LineAlignment } from './line-alignment';
export { determineTargetFilePath } from './determine-target-file';